language: node_js
stages:
  - test
  - deploy
jobs:
  include:
    - stage: test
      name: Test
      node_js:
        - 12.15.0
      script:
        - yarn lint
        - yarn test

    - stage: deploy
      name: Deploy
      script: yarn build
      node_js:
        - 12.15.0
      deploy:
        provider: npm
        skip_cleanup: true
        email: libero-npm@elifesciences.org
        api_key: $NPM_TOKEN
        on:
          tags: true
